/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ebooklogin;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author indrajit
 */
public class UsersLoginform extends javax.swing.JFrame {

    /**
     * Creates new form UsersLoginform
     */
    
    
    
    public UsersLoginform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UserNameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UserNameTextField = new javax.swing.JTextField();
        SignInButton = new javax.swing.JButton();
        LoginCancel = new javax.swing.JButton();
        UserPassTextField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        UserNameLabel.setText("UserName");

        PasswordLabel.setText("PassWord");

        SignInButton.setText("Sign In");
        SignInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInButtonActionPerformed(evt);
            }
        });

        LoginCancel.setText("Cancel");
        LoginCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(527, 527, 527)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PasswordLabel)
                    .addComponent(UserNameLabel))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(427, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LoginCancel)
                .addGap(18, 18, 18)
                .addComponent(SignInButton)
                .addGap(464, 464, 464))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserNameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignInButton)
                    .addComponent(LoginCancel))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

            JFrame jf = new JFrame("Login Page");

    private void SignInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButtonActionPerformed
        // TODO add your handling code here:
        String path = "test.txt";
        String UserNameText = "";
        String delim = ",";
        String PassWordText = "";
        UserNameText = this.UserNameTextField.getText();
        PassWordText = this.UserPassTextField.getText();
        
        HashMap<String, Users> ebookUsers = new HashMap();
        String line;

            try{
                
                
                ReadFile rf = new ReadFile(path);

                BufferedReader bufRead = rf.OpenFile();
                while((line = bufRead.readLine()) != null){
//                    //System.out.println(line);
                    String [] UserInfo = line.split(delim);
                    final String userN = UserInfo[0];
                    final String userP = UserInfo[1];
                    final String FName = UserInfo[2];
                    final String LName = UserInfo[3];
                    final String Email = UserInfo[4];
                    final String Id = UserInfo[5];
                    final String userT = UserInfo[6];
                    
                    ebookUsers.put(userN, new Users(userN, userP, FName, LName, Email, Id, userT));
                }

            }
            catch(FileNotFoundException ex){
                ex.printStackTrace();
            }
            catch(IOException e){
                e.printStackTrace();
            }
            catch(IndexOutOfBoundsException e){
            //catch(Exception e){
                e.printStackTrace();
            }
            boolean nmatch = false;
            boolean pmatch = false;
            String SuperUserType = "Super User";
            String UserType = "User";
            Users SpecialUser = null;
            String uType = "";
            if(!UserNameText.isEmpty() && !PassWordText.isEmpty()){
                for(String userName: ebookUsers.keySet()){
                if(UserNameText.equals(userName)){
                    SpecialUser = ebookUsers.get(userName);
                    nmatch = true;
                }
                if(nmatch){
                    String userP = SpecialUser.getPassWord();
                    uType = SpecialUser.getUserType();
                    if(userP.equals(PassWordText)){
//                        JOptionPane.showMessageDialog(null, "User exist Login Successful");
                        pmatch = true; 
                    }
                }
            }
            if(pmatch){
                //JOptionPane.showMessageDialog(null, "Login Successful");
                
                ////////////
                if(uType.equals(SuperUserType)){
                    //SpecialUser = ebookUsers.get(userName);
                    //display the content as admin
                    JOptionPane.showMessageDialog(null, "You are logged in as  Super user.");
                }
                else{//if(uType.equals(UserType)){
                    //display the content as user
                    JOptionPane.showMessageDialog(null, "You are logged in as registered user.");
                }
//                else{
//                    //display the content as visitor
//                    JOptionPane.showMessageDialog(null, "You are a Visitor.");
//                }
                ////////////
                cancel();
            }
            else{
                JOptionPane.showMessageDialog(null, "You are not registered user.");
            }
            }else
            {
                JOptionPane.showMessageDialog(null, "All fields are required");
            }
            //J

    }//GEN-LAST:event_SignInButtonActionPerformed

    private void LoginCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginCancelActionPerformed
        // TODO add your handling code here:
        cancel();
        ApplicationHome AH = new ApplicationHome();
        AH.setVisible(true);
    }//GEN-LAST:event_LoginCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersLoginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersLoginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersLoginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersLoginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersLoginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginCancel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton SignInButton;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JTextField UserNameTextField;
    private javax.swing.JPasswordField UserPassTextField;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

public void cancel(){
        WindowEvent winClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }
}
