/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mylastcsc221project;

import java.awt.Component;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author indrajit
 */
public class LoginForm extends javax.swing.JFrame {

    //private Component frame;

    JFrame frame = new JFrame("");

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        userName = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();

        jTextField1.setText("jTextField1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome To Employee DataBase");

        jLabel1.setText("User Name");

        jLabel2.setText("Password");

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LoginButton)
                        .addGap(148, 148, 148))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userName, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(password))
                        .addGap(115, 115, 115))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(LoginButton)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed

        String csvFilepath = "/Users/indrajit/Desktop/employee.csv";//path to the location of the .csv file
        BufferedReader br = null;
        String line = "";
        String delimiter = ",";
        String User_Name = "";
        String User_password = "";
        HashMap<String, Employee> emp = new HashMap<>();

        try {
            br = new BufferedReader(new FileReader(csvFilepath));
            

            User_Name = this.userName.getText();//this sets the inputted username by user in the text field
            User_password = this.password.getText();// this sets the inputted password by user in the password field

            while ((line = br.readLine()) != null) {

                String[] EmpInfo = line.split(delimiter);//read line by line and put each word into subsequent index of String array
                final String empUserName = EmpInfo[0];//this is first word in line 1 (row 1) at the first iteration and will be first word for line 2 in second iteration
                final String empPassword = EmpInfo[1];//samilar as above
                final String empName = EmpInfo[2];
                final String empID = EmpInfo[3];
                final String empAddress = EmpInfo[4];
                final String empFamily = EmpInfo[5];
                //Employee(String name, String address, String family, String ID, String userName, String passWord)
                emp.put(empUserName, new Employee(empName, empAddress, empFamily, empID, empUserName, empPassword));// puts key (userName) and Value (emoloyee) in the map

            }

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch(IndexOutOfBoundsException e){
            System.out.println("Wrong in CSV file");
        }
        boolean match = false;
        Employee SpecificEmp = null;
        if (!User_Name.isEmpty() && !User_password.isEmpty()) {

            for (String userName : emp.keySet()) {
                if (User_Name.equals(userName)) {
                    //Employee SpecificEmp = emp.get(userName);
                    SpecificEmp = emp.get(userName);
                    match = true;
                }
            }
            if (match) {
                String empPassW = SpecificEmp.getPassWord();

                if (empPassW.equals(User_password)) {

                    JOptionPane.showMessageDialog(frame, "Employee name: " + SpecificEmp.getName()
                            + "\nEmployee ID: " + SpecificEmp.getID() + "\nEmployee address: " + SpecificEmp.getAddress()
                            + "\nEmployee family: " + SpecificEmp.getFamily(), "Employee details", JOptionPane.PLAIN_MESSAGE);
                    System.exit(0);
                } else {
                    JOptionPane.showMessageDialog(frame, "Wrong User name or password.\nTry Again", "Warning", JOptionPane.ERROR_MESSAGE);
                    //System.exit(0);
                }
            } else {
                JOptionPane.showMessageDialog(frame, "User name does not exist.\nTry Again", "Warning", JOptionPane.ERROR_MESSAGE);
                //System.exit(0);
            }
        } else {
            JOptionPane.showMessageDialog(frame, "User name or Password missing.\nTry Again", "Warning", JOptionPane.ERROR_MESSAGE);
            //System.exit(0);
        }

    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
